title:            "smcleod dot net"
author: "Sam McLeod"
description:      'smcleod.net'
#subheading: "Really cool blog about ... something"
more: "read more"
url: "https://smcleod.net"
#baseurl: "/contrast" # comment out if in root directory

comments:
    disqus: "smcleodnet"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: false
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/sammcj/"
  - twitter: "https://twitter.com/s_mcleod/"
  - linkedin: "http://au.linkedin.com/in/sammcj/en"

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-press

paginate: 6
permalink:   /:categories/:title/
timezone:    Australia/Melbourne
future:      true
highlighter: rouge
google_analytics: UA-59178670-1
google_verify: nV3mQhSg4qnV69-hIGRP0i-KCo6Q4cOKlFcsNQ_pDqM
excerpt_separator: "<!--more-->"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]

jekyll-press:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
