source 'https://rubygems.org'

gem 'jekyll', '3.0.0.pre.beta1'
gem 'coderay'
gem 'sass'
#gem 'octopress', '~> 3.0.0.rc.33'
gem 'jekyll-sitemap'
gem 'ruby-oembed'
gem 'therubyracer'
gem 'jekyll-paginate'
