name: Check for broken links

on:
  workflow_dispatch:

# TODO: fix error 'Error: open /github/workspace/.github/main.workflow: no such file or directory'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "links"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  baseURL: "https://smcleod.net"

jobs:
  check-links:
    if: github.repository == 'sammcj/smcleod'
    strategy:
      matrix:
        environment: ['production']
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          hugo \
            --minify \
            --baseURL "${{ env.baseURL }}"
        env:
          HUGO_ENVIRONMENT: ${{ matrix.environment }}
          HUGO_ENV: ${{ matrix.environment }}

      - name: Check links
        id: check-links
        uses: marccampbell/hugo-linkcheck-action@v0.1.3
