#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: "Lint Github Actions Workflows"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main
      - master
      - "!repo-sync/**"
      - "!renovate/**"
      - "!update/pre-commit-hooks/**"
    paths:
      - ".github/**"
      - "!**/node_modules/**"

permissions:
  contents: read
  pull-requests: write
  checks: write

# One build per branch, cancel out of date builds
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-actions-workflows:
    name: Lint Actions Workflows
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3 # tag=v3
      - uses: reviewdog/action-actionlint@v1 # tag=v1
        with:
          actionlint_flags: -color -ignore 'SC2086' -ignore 'SC2129'
          fail_on_error: false
          level: error
          reporter: github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
