---
name: Typos

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: typos-action
        uses: crate-ci/typos@945d407a5fc9097f020969446a16f581612ab4df # v1.24.5
        with:
          files: |
            README.md
            content/**/*.md
